### ISSUE TITLE
Real world data share

### ISSUE THREAD

**Issue by loleg** [gperonato/archive-forge#2]
Here is a chemistry-relevant forge page. Use the two .mol files and the two corresponding NMR spectra in https://www.dropbox.com/sh/l9vhourn6145hbe/AAA1c-J2cougYT89XAJMZAOza?dl=0. One NMR spectrum is zipped, the other is in his "native" form: a folder with file structure ( you will need to zip it). Ideally we should be able to drop the folder, but we can live with asking to zip before dropping. We will need to check the content of the .zip file.... read the "acqus" and "procs" files that are inside. This will provide meta data we will write as part of the validation.

**Comment by djeanner** [comment]
This issue is completed.
